### ISSUE TITLE
setup-hadoop.sh

### ISSUE THREAD

**Issue by jhajek** [SAT-Hadoop/SetupScripts#2]
The script for setup-hadoop.sh  is crashing at these lines:

for f in $HADOOP_HOME/contrib/capacity-scheduler/*.jar; do
  if [ "$HADOOP_CLASSPATH" ]; then
    export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:$f
  else
    export HADOOP_CLASSPATH=$f
  fi
done

Is $HADOOP_HOME set in the script?  And there is no capacity-scheduler file on the system

**Comment by saipramod** [comment]
I use the absolute path of hadoop home directory and add bin and sbin to .bashrc.

**Comment by jhajek** [comment]
But where is $HADOOP_HOME defined in the script?

**Comment by saipramod** [comment]
Fixed it. It was a typo. A Big one. corrected it now. Please give it a try.

**Comment by jhajek** [comment]
Good work

Now line 132 crashes the script

    qemu: # A string representing this instance of hadoop. $USER by default.
    qemu: export HADOOP_IDENT_STRING=$USER
    qemu:
    qemu: '
    qemu: /tmp/setup-hadoop.sh: line 132: /home/vagrant/etc/hadoop/hadoop-env.sh: No such file or directory

**Comment by saipramod** [comment]
Can you force build it ? I dont understand why this part of the script is parsed. It s supposed to be just a huge string put inside a file and hadoop has to worry about it.

**Comment by jhajek** [comment]
The question is does that file exist? Is it a path problem?

**Comment by saipramod** [comment]
$HOME should be set to the path where hadoop is downloaded.

Thanks,
Sai

**Comment by jhajek** [comment]
Here is the solution:  simple typo
See Line 94
$HOME/hadoop-2.6.0/etc/hadoop/yarn-env.sh
Line 132
$HOME/etc/hadoop/hadoop-env.sh
Note the small difference.  I will make the change and update the script
