### ISSUE TITLE
Backendworker Maven Build error

### ISSUE THREAD

**Issue by jhajek** [SAT-Hadoop/SetupScripts#5]
on running the Backendworker mvn build the script fails - does it need Hadoop to be running?

Here is the build output

    qemu: mvn clean install -f ~/BackendWorker/pom.xml
    qemu: [INFO] Scanning for projects...
    qemu: [INFO]
    qemu: [INFO] ------------------------------------------------------------------------
    qemu: [INFO] Building BackendWorker 1.0-SNAPSHOT
    qemu: [INFO] ------------------------------------------------------------------------
    qemu: Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.pom
    qemu: Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.pom (640 B at 2.8 KB/sec)
    qemu: Downloading: http://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.pom
    qemu: Downloaded: http://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.pom (10 KB at 166.6 KB/sec)
    qemu: Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/3/commons-parent-3.pom
    qemu: Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/3/commons-parent-3.pom (12 KB at 288.4 KB/sec)
    qemu: Downloading: http://repo.maven.apache.org/maven2/javax/mail/mail/1.4/mail-1.4.pom
    qemu: Downloaded: http://repo.maven.apache.org/maven2/javax/mail/mail/1.4/mail-1.4.pom (993 B at 32.3 KB/sec)
    qemu: Downloading: http://repo.maven.apache.org/maven2/javax/activation/activation/1.1/activation-1.1.pom
    qemu: Downloaded: http://repo.maven.apache.org/maven2/javax/activation/activation/1.1/activation-1.1.pom (2 KB at 43.1 KB/sec)
    qemu: [WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
    qemu: Downloading: http://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
    qemu: Downloading: http://repo.maven.apache.org/maven2/javax/mail/mail/1.4/mail-1.4.jar
    qemu: Downloading: http://repo.maven.apache.org/maven2/javax/activation/activation/1.1/activation-1.1.jar
    qemu: Downloaded: http://repo.maven.apache.org/maven2/javax/activation/activation/1.1/activation-1.1.jar (62 KB at 759.3 KB/sec)
    qemu: Downloaded: http://repo.maven.apache.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar (86 KB at 921.7 KB/sec)
    qemu: Downloaded: http://repo.maven.apache.org/maven2/javax/mail/mail/1.4/mail-1.4.jar (380 KB at 2170.0 KB/sec)
    qemu: [INFO]
    qemu: [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ BackendWorker ---
    qemu: [INFO] Deleting /home/vagrant/BackendWorker/target
    qemu: [INFO]
    qemu: [INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ BackendWorker ---
    qemu: [INFO] Using 'UTF-8' encoding to copy filtered resources.
    qemu: [INFO] skip non existing resourceDirectory /home/vagrant/BackendWorker/src/main/resources
    qemu: [INFO]
    qemu: [INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ BackendWorker ---
    qemu: [INFO] Compiling 4 source files to /home/vagrant/BackendWorker/target/classes
    qemu: [INFO] ------------------------------------------------------------------------
    qemu: [INFO] BUILD FAILURE
    qemu: [INFO] ------------------------------------------------------------------------
    qemu: [INFO] Total time: 8.575s
    qemu: [INFO] Finished at: Sat Jun 20 21:42:30 UTC 2015
    qemu: [INFO] Final Memory: 14M/35M
    qemu: [INFO] ------------------------------------------------------------------------
    qemu: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project BackendWorker: Compilation failure: Compilation failure:
    qemu: [ERROR] /home/vagrant/BackendWorker/src/main/java/edu/iit/driver/Driver.java:[35,22] error: cannot find symbol
    qemu: [ERROR]
    qemu: [ERROR] could not parse error message:   symbol:   method checkForMessages()
    qemu: [ERROR] location: variable worker of type Worker
    qemu: [ERROR] /home/vagrant/BackendWorker/src/main/java/edu/iit/driver/Driver.java:36: error: cannot find symbol
    qemu: [ERROR] message = worker.getMessages();
    qemu: [ERROR] ^
    qemu: [ERROR]
    qemu: [ERROR] could not parse error message:   symbol:   method getMessages()
    qemu: [ERROR] location: variable worker of type Worker
    qemu: [ERROR] /home/vagrant/BackendWorker/src/main/java/edu/iit/driver/Driver.java:38: error: cannot find symbol
    qemu: [ERROR] job = worker.getUserJob(worker.getMessages().getBody());
    qemu: [ERROR] ^
    qemu: [ERROR]
    qemu: [ERROR] could not parse error message:   symbol:   method getMessages()
    qemu: [ERROR] location: variable worker of type Worker
    qemu: [ERROR] /home/vagrant/BackendWorker/src/main/java/edu/iit/driver/Driver.java:95: error: cannot find symbol
    qemu: [ERROR] worker.deleteMessage(message, job);
    qemu: [ERROR] ^
    qemu: [ERROR] -> [Help 1]
    qemu: [ERROR]
    qemu: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    qemu: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    qemu: [ERROR]
    qemu: [ERROR] For more information about the errors and possible solutions, please read the following articles:
    qemu: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by saipramod** [comment]
Fixed it. It was a typo due to which a section of code supposed to be commented was not. Please give it a try and let me know for any concerns.

**Comment by jhajek** [comment]
Hi - the job seems to be stuck now at one point this error is repeating over and over

to recreate - ssh into .112 from .110 and cd SetupSCripts/Packer-builscripts/backend-worker/vagrant  then ./end-to-end-vagrant-build.sh    (you may have to ps -ef | grep qemu and kill any zombie qemu processes from running before hand)

qemu: Queue already exists, moving on
    qemu: Jun 21, 2015 1:08:09 AM JobExecutionTest runWordCount
    qemu: SEVERE: null
    qemu: java.lang.NullPointerException
    qemu: at edu.iit.rabbitmq.Receive.getMessage(Receive.java:22)
    qemu: at JobExecutionTest.runWordCount(JobExecutionTest.java:48)
    qemu: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    qemu: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    qemu: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    qemu: at java.lang.reflect.Method.invoke(Method.java:606)
    qemu: at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    qemu: at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    qemu: at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    qemu: at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    qemu: at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    qemu: at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    qemu: at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    qemu: at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    qemu: at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    qemu: at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    qemu: at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    qemu: at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    qemu: at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    qemu: at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
    qemu: at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
    qemu: at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
    qemu: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    qemu: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    qemu: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    qemu: at java.lang.reflect.Method.invoke(Method.java:606)
    qemu: at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
    qemu: at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
    qemu: at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
    qemu: at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
    qemu: at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
    qemu:

**Comment by saipramod** [comment]
Please donot run the test. Just build it.  The Junit runs in a infinite
while loop.

Thanks,
Sai.

**Comment by jhajek** [comment]
Ok where are the tests?  Are they part of this command? mvn clean install -f ~/BackendWorker/pom.xml   How do I skip the tests?

**Comment by saipramod** [comment]
mvn clean install -Dmaven.test.skip=true -f ~/BackendWorker/pom.xml

**Comment by jhajek** [comment]
ok I will update the post-install-vagrant.sh that calls that and try again

**Comment by jhajek** [comment]
Ok removing the test worked build is successful
